# Generated by Django 4.2.13 on 2024-05-27 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('currency_name', models.CharField(max_length=100)),
                ('currency_code', models.CharField(max_length=10)),
                ('currency_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('currency', models.CharField(max_length=50)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('change', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
            options={
                'unique_together': {('date', 'currency')},
            },
        ),
    ]
