# Generated by Django 4.2.13 on 2024-05-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_app', '0002_alter_countrycurrency_currency_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param_name', models.CharField(max_length=50, unique=True)),
                ('param_value', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RelativeChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('currency', models.CharField(max_length=50)),
                ('relative_change', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
            options={
                'unique_together': {('date', 'currency')},
            },
        ),
    ]
